name: Publish Docker image of ROS Melodic

on:
  push:
    branches: [ main ]
    paths:
      - "./Docker/melodic/*"
      - ".github/workflows/docker-publish-melodic.yml"

jobs:
  push_to_registry:
    name: Build and Push docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      # login against a docker registry except on pr
      # https://github.com/docker/login-action
      - name: log in to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      # extract metadata (tags, labels) for docker
      # https://github.com/docker/metadata-action
      - name: extract docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: rishavsingh0/ros

      # build and push docker image with buildx (don't push on pr)
      # https://github.com/docker/build-push-action
      - name: build and push docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Docker/melodic/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: rishavsingh0/ros:melodic
          labels: ${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64, linux/arm64, linux/arm/v7, darwin/amd64
